_1stERP.lang={
	s_FunctionList					:"功能列表",		
	
	s_Title_Basic						:"基础部分",
	s_Product_Info					:"存货资料 -- T04",
	s_Product_Price					:"存货价格 -- T05",
	
	s_Title_FinanceManager	: "财务管理",
	s_Money_In							: "收入录入 -- T02",
	s_Money_Out							: "支出录入 -- T02",
	s_Money_Move						: "资金调动 -- T02",	
	s_Sales_Earning					: "销售收款 -- T02",	
	s_Purchase_Paying				: "采购付款 -- T02",
	s_Finance_Summary				: "财务统计",
	s_Finance_Running				: "流水帐查询",
	
	s_Title_SalesManager		:"销售管理",
	s_Customer_Info					:"客户信息	-- T03|T05",
	s_Customer_Log					:"客户关系管理-- T03|T05",
	
	s_Sales_Order						:"销售订单 	-- T03|T05",		
	s_Sales_Output					:"销售出货单-- T04",
	s_Return_Order					:"退货单		-- T03|T05",
	s_Return_Output					:"退货出货单-- T04",
	
	s_Sales_Order_History		:"销售订单统计",	
	s_Return_Order_History	:"退货单统计",	
	s_Output_History				:"出货记录",	
	s_CustomerBuyDetail			:"客户购买力分析",
	s_ProductSalesDetail		:"产品销售分析",
	
	
	
	s_Title_Supplier				:"供应商部分",
	s_Supplier_Info					:"供应商信息	--T03",
	
	s_Purchase_Order				:"采购订单	--T03T04",
	s_Purchase_Input				:"采购收货	--T04",
	
	s_Purchase_Order_History:"采购订单统计",
	
	
	s_Title_StockManage			:"仓库管理",
	s_Stock_Info						:"仓库信息	--T04",	
	s_Stock_Debit						:"借贷记录	--T04",
	s_Add_LL_Order					:"领料单		--T03T04T05",
	s_Add_TL_Order					:"退料单		--T04",
	s_Add_CPRC_Order				:"产品进仓单--T04",	
	s_Add_BF_Order					:"报废单		--T05",
	s_Add_PD_Order					:"库存盘点	--T04",
	
	s_Stock_Balance					:"库存统计",
	s_Stock_Running					:"库存流水信息",
	
	
	s_Title_Other						:"其他部分",
	s_Staff_Info						:"职员信息",
	s_Bank_Info							:"银行信息",
	s_Currency_Info					:"货币信息",
	s_Other									:"杂项",
		
	s_Title_Show						:"::显示::",					
	s_Title_Add							:"::添加::",					
	s_Title_Edit						:"::编辑::",					
	s_Title_Delete					:"::删除::",			
	
	
	s_Product								:"产品",
	s_Materiel							:"物料",
		
	s_id										:"id",
	s_ProductNo							:"存货型号",
	s_ProductType						:"存货类别",
	s_productSpec						:"规格",		
	s_Remark								:"备注",
	s_Price									:"价格",
	
	
	
	s_ShortName					: "简称",
	s_AreaCode					: "地区",
	s_LongName					: "全称",
	s_ContactMan				: "联系人",
	s_ContactMobile			: "联系手机",		
	s_Tel								: "电话",   	
	s_Fax								: "传真",   
	s_Post							: "邮编",	
	s_Address						: "地址", 
	s_Url								: "网址",  
	
	s_DBServerIP						:"数据库IP", 					
	s_DBServerUser					:"数据库帐号", 				
	s_DBServerPsd						:"数据库密码", 				
	s_AdminUser							:"管理帐号", 					
	s_AdminPsd							:"管理密码", 					
	s_Login									:"登陆", 							
	s_LoginTooFast					:"请不要频繁登陆", 		
	s_UserError							:"帐号或密码错误", 		
	s_DBConnFail						:"数据库连接失败", 		
	s_SearchExprieUser			:"查看将要过期用户信息",			
	s_View									:"查看",					
	s_Quest									:"请求",					
	s_Success								:"成功",					
	s_Fail									:"失败",					
	s_Timeout								:"超时",					
	s_Alert									:"警告",		
		
	s_Show									:"显示",					
	s_Add										:"添加", 					
	s_Modify								:"修改",	
	s_Del										:"删除", 		 				
	
	s_First									:"|<<第一条",
	s_Prev									:"<<上一条",
	s_Next									:"下一条>>",
	s_Last									:"最后一条>>|",
	s_Clear									:"清除",					
	s_User 						:"帐号",    			
	s_FName 					:"姓氏",    		
	s_LName 					:"名字",    		
	s_Password 				:"密码",    		
	s_Emaill					:"邮箱",    		
	s_Privilege				:"权限", 			
	s_SuperUser				:"超级用户", 	
	s_OwnUser					:"所属子用户", 
	s_AllUser					:"所有用户", 	
	s_CompanyName 		:"公司",    		
	s_Search					:"查询",				
	s_ShowAll					:"显示所有",		
	s_Refresh					:"刷新",				
	s_Log							:"日志",				
	s_Exit						:"退出",				
	s_PleaseConfrim		:"&nbsp;&nbsp;&nbsp;&nbsp;请确认?&nbsp;&nbsp;&nbsp;&nbsp;",		
	s_PleaseSelect		:"&nbsp;&nbsp;&nbsp;&nbsp;请先选择!&nbsp;&nbsp;&nbsp;&nbsp;",		
	s_ReinputPassWord	:"重输密码",		
	s_PLSSelectFirst	:"请先选择!",
	s_Submit					:"提交",					
	s_Ok							:"确定",					
	s_Close						:"关闭",					
	s_License						:"车牌号码",   			
	s_Sim								:"终端SIM卡号", 		  
	s_DEType						:"终端类型", 				
	s_DEUID							:"终端序列号", 			
	s_Money							:"交费", 						
	s_UsedDay						:"可使用天数", 			
	s_GiftDay						:"赠送天数", 				
	s_PrevExpire				:"上次到期时间", 		
	s_PriceRule					:"收费标准(元/月)",	
	s_CurExpire					:"续费到期时间", 		
	s_StartTime					:"开始时间", 				
	s_EndTime						:"结束时间", 				
	s_ExpireReport			:"交费到期报表", 		
	s_BelongUser				:"所属用户", 				
	s_CarNotOwnByUser		:"不属于任何用户", 	
	s_DatabaseStatus			:"数据库状态", 				
	s_TableName						:"表名称", 						
	s_RecordCount					:"记录统计", 					
	s_NowDBTableCount			:"数据库表统计", 			
	s_UseableSpaceMB			:"可用空间(MB)", 			
	s_DiskPrartition			:"磁盘分区", 					
	s_ServerDiskUseSpace	:"服务器磁盘可用空间", 
	s_DBFileStatus				:"数据库文件状态", 		
	s_FileName						:"文件名", 						
	s_FileURl							:"文件路径", 					
	s_SizeMB							:"容量(MB)", 					
	s_SaveTrackDay				:"保存轨迹天数", 			
	s_SaveImageURl				:"保存图片路径", 			
	s_SaveImageCount			:"每车存照片数", 			
	s_NowClearTrackTable	:"立即清理轨迹表", 		
	s_Save								:"保存", 							
	s_OutputExcel		:"导出Excel文件", 						
	s_UseTimeout			:"系统已自动退出!请重新登陆", 
	s_downloadBusyWait		:"服务器忙,请稍后再试",	
	s_NowClearTrackAlert	:"此操作会导致数据库服务器消耗大量系统资源,请谨慎操作!<br>由于处理时间较长,本页面可能失去响应,属于正常现象,请忽重复提交!"
	
	
	
	
};